ALTER TABLE users ADD COLUMN role VARCHAR(255) NOT NULL DEFAULT '';

UPDATE users SET role = 'USER';
UPDATE users SET role = 'ADMIN' WHERE id IN (SELECT id FROM users ORDER BY id LIMIT 1);
ALTER TABLE users ALTER COLUMN role DROP DEFAULT;